name = "VisualExamples"
uuid = "1f886864-7814-4baf-a1b6-b6ae7c84244d"
authors = ["Aaron Kaw <aaronjkaw@gmail.com> and contributors"]
version = "1.0.0-DEV"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
VisualMakieExt = "Makie"
VisualPlotsExt = "Plots"

[compat]
Makie = "0.21"
Plots = "1.40"
julia = "1.10"
